# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rishi Chordia
email: rishichordia@microsoft.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm a Computer Science graduate from IIT Roorkee, currently working at Microsoft India.

# My passion for mathematics, computer science and machine learning has led me to pursue research in Robotics and NLP. 
# I'm looking for opportunities as I graduate in 2024, please reach out!
baseurl: "" # the subpath of your site, e.g. /blog
url: "rishichordia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: rishi-chordia-6a4052193 
github_username:  rishichordia

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

resume_avatar:                  "true"
resume_name:                    "Rishi Chordia"
resume_title:                   "Diving into the world of computer systems which is hidden behind abstraction."

# used for the contact button in _layouts/resume.html
resume_contact_email:           "rishichordia@microsoft.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "91-8197914054"
resume_contact_address:         "Microsoft IDC, Bangalore India"

resume_header_contact_info:     "Microsoft IDC, Bangalore India • 91-8197914054 • rishichordia@microsoft.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a software engineer at Microsoft India working as a big data platform engineer. I have been exploring the world of computers since 2019 and am fascinated by how the abstract entitties in computing worlds come together to make something beautiful. </p>
<p> My areas of academic interest include Operating Systems, Distributed systems and Computer Architecture which have been the prime area of focus in my undergrad years at IIT Roorkee. I am curious about the fundamental working principles behind computer systems. I would love to explore the worlds of systems. Apart from working, I like to play volleyball and swim. Fitness of mind comes from fitness of body, hence I try to play sports or hit the gym atleast 4 times a week. :)</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_publication:     false
resume_section_interests:       false
resume_section_teaching:        true

# Navigation
show_navigation: true
show_introduction_nav_link: true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/rishichordia"
  # resume_twitter_url:           "https://twitter.com/yashsharma0906"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/rishi-chordia-6a4052193/"
  resume_instagram_url:         "https://www.instagram.com/star_dust_1206/"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
